Name:           ros-melodic-py-trees-ros
Version:        0.5.16
Release:        0%{?dist}
Summary:        ROS py_trees_ros package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/py_trees
Source0:        %{name}-%{version}.tar.gz

Requires:       python-rospkg
Requires:       python-termcolor
Requires:       ros-melodic-actionlib
Requires:       ros-melodic-actionlib-msgs
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-move-base-msgs
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-py-trees
Requires:       ros-melodic-py-trees-msgs
Requires:       ros-melodic-rosbag
Requires:       ros-melodic-rospy
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-unique-id
Requires:       ros-melodic-uuid-msgs
BuildRequires:  python-setuptools
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-py-trees
BuildRequires:  ros-melodic-python-qt-binding
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rosunit

%description
Ros extensions and behaviours for py_trees.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Feb 02 2019 Daniel Stonier <d.stonier@gmail.com> - 0.5.16-0
- Autogenerated by Bloom

* Sat Feb 02 2019 Daniel Stonier <d.stonier@gmail.com> - 0.5.15-0
- Autogenerated by Bloom

* Sat Aug 25 2018 Daniel Stonier <d.stonier@gmail.com> - 0.5.14-0
- Autogenerated by Bloom

